# Generated by Django 3.1.5 on 2021-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_inputoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputoutput',
            name='input_data',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='inputoutput',
            name='output_data',
            field=models.FileField(upload_to=''),
        ),
    ]
