# Generated by Django 3.1.5 on 2021-05-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20210503_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputoutput',
            name='input_data',
            field=models.FileField(upload_to='problems/io/input/'),
        ),
        migrations.AlterField(
            model_name='inputoutput',
            name='output_data',
            field=models.FileField(upload_to='problems/io/output/'),
        ),
    ]
