# Generated by Django 3.1.5 on 2021-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20210519_1038'),
        ('problems', '0006_auto_20210505_1817'),
    ]

    operations = [
    ]
