# Generated by Django 3.1.5 on 2021-06-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_merge_20210519_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=50),
        ),
    ]
