# Generated by Django 3.1.2 on 2021-04-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solved',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='solved',
            old_name='user_id',
            new_name='user',
        ),
    ]
