# Generated by Django 3.1.5 on 2021-06-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_solved_cases_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
