# Generated by Django 3.1.5 on 2021-06-13 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_solved_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
